### ISSUE TITLE
Texture conversion error

### ISSUE THREAD

**Issue by Torphedo** [KillzXGaming/BfresPlatformConverter#2]
When converting [one of haldir307's mods](https://gamebanana.com/mods/284846), I encountered an error when converting the shield textures. Here's the [affected texture files](https://github.com/KillzXGaming/BfresPlatformConverter/files/7509402/textures.zip), and the error thrown:

```
Unhandled Exception: System.ArgumentException: Source array was not long enough. Check srcIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
   at Syroot.NintenTools.Bfres.Swizzling.GX2.Decode(GX2Surface tex, Int32 ArrayIndex, Int32 MipIndex, String DebugTextureName)
   at Syroot.NintenTools.Bfres.WiiU.Texture.GetDeswizzledData(Int32 arrayLevel, Int32 mipLevel)
   at Syroot.NintenTools.Bfres.Switch.SwitchTexture.FromWiiU(Texture textureU)
   at Syroot.NintenTools.Bfres.PlatformConverters.TextureConverter.CreateBNTX(List`1 textureList)
   at Syroot.NintenTools.Bfres.ResFile.ConvertTexturesToBntx(List`1 textures)
   at Syroot.NintenTools.Bfres.ResFile.ChangePlatform(Boolean isSwitch, Int32 alignment, Byte versionA, Byte versionB, Byte versionC, Byte versionD, ConverterHandle handle)
   at BfresPlatformConverter.Program.Main(String[] args) in C:\Users\Nathan\Documents\GitHub\GLEngine\BfresLibrary\BfresPlatformConverter\Program.cs:line 70
```

**Comment by Lioniox** [comment]
I have the same problem It isn't converting .Tex(number).sbfres files
